config/routes.rb
Rails.application.routes.draw do
  resources :usuario_intranets
  resources :oferta
  resources :detalle_pedidos
  resources :pedidos
  resources :productos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/pedido.rb
class Pedido < ApplicationRecord
end

app/controllers/pedidos_controller.rb
class PedidosController < ApplicationController
  before_action :set_pedido, only: %i[ show edit update destroy ]

  # GET /pedidos or /pedidos.json
  def index
    @pedidos = Pedido.all
  end

  # GET /pedidos/1 or /pedidos/1.json
  def show
  end

  # GET /pedidos/new
  def new
    @pedido = Pedido.new
  end

  # GET /pedidos/1/edit
  def edit
  end

  # POST /pedidos or /pedidos.json
  def create
    @pedido = Pedido.new(pedido_params)

    respond_to do |format|
      if @pedido.save
        format.html { redirect_to @pedido, notice: "Pedido was successfully created." }
        format.json { render :show, status: :created, location: @pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /pedidos/1 or /pedidos/1.json
  def update
    respond_to do |format|
      if @pedido.update(pedido_params)
        format.html { redirect_to @pedido, notice: "Pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pedidos/1 or /pedidos/1.json
  def destroy
    @pedido.destroy!

    respond_to do |format|
      format.html { redirect_to pedidos_path, status: :see_other, notice: "Pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pedido
      @pedido = Pedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def pedido_params
      params.require(:pedido).permit(:id_pedido, :dni, :fecha_pedido, :total)
    end
end

app/helpers/pedidos_helper.rb
module PedidosHelper
end

app/views/pedidos/_form.html.erb
<%= form_with(model: pedido) do |form| %>
  <% if pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(pedido.errors.count, "error") %> prohibited this pedido from being saved:</h2>

      <ul>
        <% pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id_pedido, style: "display: block" %>
    <%= form.number_field :id_pedido %>
  </div>

  <div>
    <%= form.label :dni, style: "display: block" %>
    <%= form.number_field :dni %>
  </div>

  <div>
    <%= form.label :fecha_pedido, style: "display: block" %>
    <%= form.date_field :fecha_pedido %>
  </div>

  <div>
    <%= form.label :total, style: "display: block" %>
    <%= form.text_field :total %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/pedidos/_pedido.html.erb
<div id="<%= dom_id pedido %>">
  <p>
    <strong>Id pedido:</strong>
    <%= pedido.id_pedido %>
  </p>

  <p>
    <strong>Dni:</strong>
    <%= pedido.dni %>
  </p>

  <p>
    <strong>Fecha pedido:</strong>
    <%= pedido.fecha_pedido %>
  </p>

  <p>
    <strong>Total:</strong>
    <%= pedido.total %>
  </p>

</div>

app/views/pedidos/edit.html.erb
<% content_for :title, "Editing pedido" %>

<h1>Editing pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Show this pedido", @pedido %> |
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Pedidos" %>

<h1>Pedidos</h1>

<div id="pedidos">
  <% @pedidos.each do |pedido| %>
    <%= render pedido %>
    <p>
      <%= link_to "Show this pedido", pedido %>
    </p>
  <% end %>
</div>

<%= link_to "New pedido", new_pedido_path %>

app/views/pedidos/new.html.erb
<% content_for :title, "New pedido" %>

<h1>New pedido</h1>

<%= render "form", pedido: @pedido %>

<br>

<div>
  <%= link_to "Back to pedidos", pedidos_path %>
</div>

app/views/pedidos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @pedido %>

<div>
  <%= link_to "Edit this pedido", edit_pedido_path(@pedido) %> |
  <%= link_to "Back to pedidos", pedidos_path %>

  <%= button_to "Destroy this pedido", @pedido, method: :delete %>
</div>