config/routes.rb
Rails.application.routes.draw do
  resources :usuario_intranets
  resources :oferta
  resources :detalle_pedidos
  resources :pedidos
  resources :productos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/detalle_pedido.rb
class DetallePedido < ApplicationRecord
end

app/controllers/detalle_pedidos_controller.rb
class DetallePedidosController < ApplicationController
  before_action :set_detalle_pedido, only: %i[ show edit update destroy ]

  # GET /detalle_pedidos or /detalle_pedidos.json
  def index
    @detalle_pedidos = DetallePedido.all
  end

  # GET /detalle_pedidos/1 or /detalle_pedidos/1.json
  def show
  end

  # GET /detalle_pedidos/new
  def new
    @detalle_pedido = DetallePedido.new
  end

  # GET /detalle_pedidos/1/edit
  def edit
  end

  # POST /detalle_pedidos or /detalle_pedidos.json
  def create
    @detalle_pedido = DetallePedido.new(detalle_pedido_params)

    respond_to do |format|
      if @detalle_pedido.save
        format.html { redirect_to @detalle_pedido, notice: "Detalle pedido was successfully created." }
        format.json { render :show, status: :created, location: @detalle_pedido }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @detalle_pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /detalle_pedidos/1 or /detalle_pedidos/1.json
  def update
    respond_to do |format|
      if @detalle_pedido.update(detalle_pedido_params)
        format.html { redirect_to @detalle_pedido, notice: "Detalle pedido was successfully updated." }
        format.json { render :show, status: :ok, location: @detalle_pedido }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @detalle_pedido.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /detalle_pedidos/1 or /detalle_pedidos/1.json
  def destroy
    @detalle_pedido.destroy!

    respond_to do |format|
      format.html { redirect_to detalle_pedidos_path, status: :see_other, notice: "Detalle pedido was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_detalle_pedido
      @detalle_pedido = DetallePedido.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def detalle_pedido_params
      params.require(:detalle_pedido).permit(:id_detalle, :id_pedido, :id_producto)
    end
end

app/helpers/detalle_pedidos_helper.rb
module DetallePedidosHelper
end

app/views/detalle_pedidos/_detalle_pedido.html.erb
<div id="<%= dom_id detalle_pedido %>">
  <p>
    <strong>Id detalle:</strong>
    <%= detalle_pedido.id_detalle %>
  </p>

  <p>
    <strong>Id pedido:</strong>
    <%= detalle_pedido.id_pedido %>
  </p>

  <p>
    <strong>Id producto:</strong>
    <%= detalle_pedido.id_producto %>
  </p>

</div>

app/views/detalle_pedidos/_form.html.erb
<%= form_with(model: detalle_pedido) do |form| %>
  <% if detalle_pedido.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(detalle_pedido.errors.count, "error") %> prohibited this detalle_pedido from being saved:</h2>

      <ul>
        <% detalle_pedido.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id_detalle, style: "display: block" %>
    <%= form.number_field :id_detalle %>
  </div>

  <div>
    <%= form.label :id_pedido, style: "display: block" %>
    <%= form.number_field :id_pedido %>
  </div>

  <div>
    <%= form.label :id_producto, style: "display: block" %>
    <%= form.number_field :id_producto %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/detalle_pedidos/edit.html.erb
<% content_for :title, "Editing detalle pedido" %>

<h1>Editing detalle pedido</h1>

<%= render "form", detalle_pedido: @detalle_pedido %>

<br>

<div>
  <%= link_to "Show this detalle pedido", @detalle_pedido %> |
  <%= link_to "Back to detalle pedidos", detalle_pedidos_path %>
</div>

app/views/detalle_pedidos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Detalle pedidos" %>

<h1>Detalle pedidos</h1>

<div id="detalle_pedidos">
  <% @detalle_pedidos.each do |detalle_pedido| %>
    <%= render detalle_pedido %>
    <p>
      <%= link_to "Show this detalle pedido", detalle_pedido %>
    </p>
  <% end %>
</div>

<%= link_to "New detalle pedido", new_detalle_pedido_path %>

app/views/detalle_pedidos/new.html.erb
<% content_for :title, "New detalle pedido" %>

<h1>New detalle pedido</h1>

<%= render "form", detalle_pedido: @detalle_pedido %>

<br>

<div>
  <%= link_to "Back to detalle pedidos", detalle_pedidos_path %>
</div>

app/views/detalle_pedidos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @detalle_pedido %>

<div>
  <%= link_to "Edit this detalle pedido", edit_detalle_pedido_path(@detalle_pedido) %> |
  <%= link_to "Back to detalle pedidos", detalle_pedidos_path %>

  <%= button_to "Destroy this detalle pedido", @detalle_pedido, method: :delete %>
</div>