config/routes.rb
Rails.application.routes.draw do
  resources :usuario_intranets
  resources :oferta
  resources :detalle_pedidos
  resources :pedidos
  resources :productos
  resources :clientes
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/producto.rb
class Producto < ApplicationRecord
end

app/controllers/productos_controller.rb
class ProductosController < ApplicationController
  before_action :set_producto, only: %i[ show edit update destroy ]

  # GET /productos or /productos.json
  def index
    @productos = Producto.all
  end

  # GET /productos/1 or /productos/1.json
  def show
  end

  # GET /productos/new
  def new
    @producto = Producto.new
  end

  # GET /productos/1/edit
  def edit
  end

  # POST /productos or /productos.json
  def create
    @producto = Producto.new(producto_params)

    respond_to do |format|
      if @producto.save
        format.html { redirect_to @producto, notice: "Producto was successfully created." }
        format.json { render :show, status: :created, location: @producto }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /productos/1 or /productos/1.json
  def update
    respond_to do |format|
      if @producto.update(producto_params)
        format.html { redirect_to @producto, notice: "Producto was successfully updated." }
        format.json { render :show, status: :ok, location: @producto }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @producto.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /productos/1 or /productos/1.json
  def destroy
    @producto.destroy!

    respond_to do |format|
      format.html { redirect_to productos_path, status: :see_other, notice: "Producto was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_producto
      @producto = Producto.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def producto_params
      params.require(:producto).permit(:id_producto, :nombre, :categoria, :precio)
    end
end

app/helpers/productos_helper.rb
module ProductosHelper
end

app/views/productos/_form.html.erb
<%= form_with(model: producto) do |form| %>
  <% if producto.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(producto.errors.count, "error") %> prohibited this producto from being saved:</h2>

      <ul>
        <% producto.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div>
    <%= form.label :id_producto, style: "display: block" %>
    <%= form.number_field :id_producto %>
  </div>

  <div>
    <%= form.label :nombre, style: "display: block" %>
    <%= form.text_field :nombre %>
  </div>

  <div>
    <%= form.label :categoria, style: "display: block" %>
    <%= form.text_field :categoria %>
  </div>

  <div>
    <%= form.label :precio, style: "display: block" %>
    <%= form.text_field :precio %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/productos/_producto.html.erb
<div id="<%= dom_id producto %>">
  <p>
    <strong>Id producto:</strong>
    <%= producto.id_producto %>
  </p>

  <p>
    <strong>Nombre:</strong>
    <%= producto.nombre %>
  </p>

  <p>
    <strong>Categoria:</strong>
    <%= producto.categoria %>
  </p>

  <p>
    <strong>Precio:</strong>
    <%= producto.precio %>
  </p>

</div>

app/views/productos/edit.html.erb
<% content_for :title, "Editing producto" %>

<h1>Editing producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Show this producto", @producto %> |
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/index.html.erb
<p style="color: green"><%= notice %></p>

<% content_for :title, "Productos" %>

<h1>Productos</h1>

<div id="productos">
  <% @productos.each do |producto| %>
    <%= render producto %>
    <p>
      <%= link_to "Show this producto", producto %>
    </p>
  <% end %>
</div>

<%= link_to "New producto", new_producto_path %>

app/views/productos/new.html.erb
<% content_for :title, "New producto" %>

<h1>New producto</h1>

<%= render "form", producto: @producto %>

<br>

<div>
  <%= link_to "Back to productos", productos_path %>
</div>

app/views/productos/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @producto %>

<div>
  <%= link_to "Edit this producto", edit_producto_path(@producto) %> |
  <%= link_to "Back to productos", productos_path %>

  <%= button_to "Destroy this producto", @producto, method: :delete %>
</div>